// Standard Node.js runtime (more compatible than Edge for external API calls)
export const config = {
  maxDuration: 30,
};

export default async function handler(req, res) {
  // CORS headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    // Read raw body
    const chunks = [];
    for await (const chunk of req) {
      chunks.push(chunk);
    }
    const buffer = Buffer.concat(chunks);

    // Get token exclusively from server-side environment variable (never exposed to users)
    const hfToken = process.env.HF_TOKEN || '';

    if (!hfToken) {
      return res.status(500).json({
        error: 'Server configuration error: HF_TOKEN environment variable is not set.',
      });
    }

    // Try multiple API URLs for resilience (both standard and modern Hugging Face routers)
    const API_URLS = [
      'https://api-inference.huggingface.co/models/umm-maybe/AI-image-detector',
      'https://router.huggingface.co/hf-inference/models/umm-maybe/AI-image-detector'
    ];

    let lastError = null;
    let hfRes = null;

    for (const apiEntry of API_URLS) {
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 20000);

      try {
        hfRes = await fetch(apiEntry, {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${hfToken.trim()}`,
            'Content-Type': 'application/octet-stream',
          },
          body: buffer,
          signal: controller.signal,
        });

        clearTimeout(timeoutId);
        if (hfRes.ok || hfRes.status === 503 || hfRes.status === 401 || hfRes.status === 403) {
          break; // Stop trying URLs if we got a definitive model or auth response
        }
        lastError = `Status ${hfRes.status}: ${await hfRes.text().catch(() => '')}`;
      } catch (fetchErr) {
        clearTimeout(timeoutId);
        lastError = fetchErr.message || String(fetchErr);
      }
    }

    if (!hfRes) {
      return res.status(502).json({
        error: `Could not reach Hugging Face API. Last connection error: ${lastError}`,
      });
    }

    const bodyText = await hfRes.text();

    if (hfRes.status === 401 || hfRes.status === 403) {
      return res.status(500).json({
        error: 'Server configuration error: Hugging Face token is invalid or expired.',
      });
    }

    if (hfRes.status === 503) {
      let waitSecs = 20;
      try {
        const parsed = JSON.parse(bodyText);
        if (parsed.estimated_time) waitSecs = Math.ceil(parsed.estimated_time);
      } catch (_) {}
      return res.status(503).json({
        error: `Model is loading. Please wait ${waitSecs} seconds and try again.`,
      });
    }

    if (!hfRes.ok) {
      return res.status(502).json({
        error: `Hugging Face returned ${hfRes.status}: ${bodyText.slice(0, 200)}`,
      });
    }

    let hfData;
    try {
      hfData = JSON.parse(bodyText);
    } catch (_) {
      return res.status(502).json({ error: `Invalid JSON from Hugging Face: ${bodyText.slice(0, 200)}` });
    }

    // Call Gemini API if key is configured
    const geminiApiKey = process.env.GEMINI_API_KEY;
    let geminiData = null;

    if (geminiApiKey) {
      try {
        const base64Image = buffer.toString('base64');
        const geminiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${geminiApiKey}`;
        
        const geminiRes = await fetch(geminiUrl, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            contents: [
              {
                parts: [
                  {
                    text: 'Analyze this image and determine the probability that it was generated by an AI (0-100%). Return your response strictly as a JSON object with this exact schema: { "ai_score": number, "reasoning": string[] }. The "reasoning" array must contain 3-4 bullet points explaining specific artifacts, lighting, physics, texture details, or anatomy observations.'
                  },
                  {
                    inlineData: {
                      mimeType: 'image/jpeg',
                      data: base64Image
                    }
                  }
                ]
              }
            ],
            generationConfig: {
              responseMimeType: 'application/json'
            }
          })
        });

        if (geminiRes.ok) {
          const geminiJson = await geminiRes.json();
          const textResponse = geminiJson.candidates?.[0]?.content?.parts?.[0]?.text;
          if (textResponse) {
            let cleanedText = textResponse.trim();
            if (cleanedText.startsWith('```')) {
              cleanedText = cleanedText.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '');
            }
            geminiData = JSON.parse(cleanedText);
          }
        } else {
          console.error('[detect] Gemini API error status:', geminiRes.status, await geminiRes.text().catch(() => ''));
        }
      } catch (geminiErr) {
        console.error('[detect] Gemini integration error:', geminiErr);
      }
    }

    // Combine results
    let combinedScore = 0;
    let hfScore = 0;

    if (Array.isArray(hfData)) {
      const fakeResult = hfData.find(r => r.label.toLowerCase().includes('artificial') || r.label.toLowerCase().includes('fake'));
      if (fakeResult) {
        hfScore = fakeResult.score * 100;
      } else {
        const realResult = hfData.find(r => r.label.toLowerCase().includes('human') || r.label.toLowerCase().includes('real'));
        if (realResult) {
          hfScore = (1 - realResult.score) * 100;
        }
      }
    }

    if (geminiData) {
      // Blend: 50% Hugging Face, 50% Gemini
      combinedScore = Math.round((hfScore * 0.5) + (geminiData.ai_score * 0.5));
    } else {
      combinedScore = Math.round(hfScore);
    }

    return res.status(200).json({
      hfResults: hfData,
      hfScore: Math.round(hfScore),
      geminiResults: geminiData,
      combinedScore: combinedScore,
      geminiActive: !!geminiData
    });

  } catch (err) {
    console.error('[detect] Unhandled error:', err);
    return res.status(500).json({ error: err.message || 'Internal server error' });
  }
}
